services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env.${DEV_ENV:-example}
    networks:
      - database-network
    volumes:
      - database-data:/var/lib/postgresql/data/
      # - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql # SQL script for seeding db with data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 30s
    #   timeout: 10s

networks:
  database-network:
    driver: bridge

volumes:
  database-data: