services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env.${DEV_ENV:-example}
    networks:
      - db-network
    volumes:
      - db-data:/var/lib/postgresql/data/
      # - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql # SQL script for seeding db with data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  db-network:
    driver: bridge
  
volumes:
  db-data: