// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CharactersColumns holds the columns for the "characters" table.
	CharactersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// CharactersTable holds the schema information for the "characters" table.
	CharactersTable = &schema.Table{
		Name:       "characters",
		Columns:    CharactersColumns,
		PrimaryKey: []*schema.Column{CharactersColumns[0]},
	}
	// MoviesColumns holds the columns for the "movies" table.
	MoviesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Unique: true},
		{Name: "year", Type: field.TypeInt},
	}
	// MoviesTable holds the schema information for the "movies" table.
	MoviesTable = &schema.Table{
		Name:       "movies",
		Columns:    MoviesColumns,
		PrimaryKey: []*schema.Column{MoviesColumns[0]},
	}
	// MovieQuotesColumns holds the columns for the "movie_quotes" table.
	MovieQuotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "quote", Type: field.TypeString},
		{Name: "character_quotes", Type: field.TypeInt},
		{Name: "movie_quotes", Type: field.TypeInt},
	}
	// MovieQuotesTable holds the schema information for the "movie_quotes" table.
	MovieQuotesTable = &schema.Table{
		Name:       "movie_quotes",
		Columns:    MovieQuotesColumns,
		PrimaryKey: []*schema.Column{MovieQuotesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "movie_quotes_characters_quotes",
				Columns:    []*schema.Column{MovieQuotesColumns[2]},
				RefColumns: []*schema.Column{CharactersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "movie_quotes_movies_quotes",
				Columns:    []*schema.Column{MovieQuotesColumns[3]},
				RefColumns: []*schema.Column{MoviesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CharactersTable,
		MoviesTable,
		MovieQuotesTable,
	}
)

func init() {
	MovieQuotesTable.ForeignKeys[0].RefTable = CharactersTable
	MovieQuotesTable.ForeignKeys[1].RefTable = MoviesTable
}
