// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/category"
	"api/ent/character"
	"api/ent/movie"
	"api/ent/moviequote"
	"api/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MovieUpdate is the builder for updating Movie entities.
type MovieUpdate struct {
	config
	hooks    []Hook
	mutation *MovieMutation
}

// Where appends a list predicates to the MovieUpdate builder.
func (mu *MovieUpdate) Where(ps ...predicate.Movie) *MovieUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetUpdatedAt sets the "updated_at" field.
func (mu *MovieUpdate) SetUpdatedAt(t time.Time) *MovieUpdate {
	mu.mutation.SetUpdatedAt(t)
	return mu
}

// SetTitle sets the "title" field.
func (mu *MovieUpdate) SetTitle(s string) *MovieUpdate {
	mu.mutation.SetTitle(s)
	return mu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (mu *MovieUpdate) SetNillableTitle(s *string) *MovieUpdate {
	if s != nil {
		mu.SetTitle(*s)
	}
	return mu
}

// SetYear sets the "year" field.
func (mu *MovieUpdate) SetYear(i int) *MovieUpdate {
	mu.mutation.ResetYear()
	mu.mutation.SetYear(i)
	return mu
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (mu *MovieUpdate) SetNillableYear(i *int) *MovieUpdate {
	if i != nil {
		mu.SetYear(*i)
	}
	return mu
}

// AddYear adds i to the "year" field.
func (mu *MovieUpdate) AddYear(i int) *MovieUpdate {
	mu.mutation.AddYear(i)
	return mu
}

// AddCategoryIDs adds the "category" edge to the Category entity by IDs.
func (mu *MovieUpdate) AddCategoryIDs(ids ...int) *MovieUpdate {
	mu.mutation.AddCategoryIDs(ids...)
	return mu
}

// AddCategory adds the "category" edges to the Category entity.
func (mu *MovieUpdate) AddCategory(c ...*Category) *MovieUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return mu.AddCategoryIDs(ids...)
}

// AddCharacterIDs adds the "characters" edge to the Character entity by IDs.
func (mu *MovieUpdate) AddCharacterIDs(ids ...int) *MovieUpdate {
	mu.mutation.AddCharacterIDs(ids...)
	return mu
}

// AddCharacters adds the "characters" edges to the Character entity.
func (mu *MovieUpdate) AddCharacters(c ...*Character) *MovieUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return mu.AddCharacterIDs(ids...)
}

// AddQuoteIDs adds the "quotes" edge to the MovieQuote entity by IDs.
func (mu *MovieUpdate) AddQuoteIDs(ids ...int) *MovieUpdate {
	mu.mutation.AddQuoteIDs(ids...)
	return mu
}

// AddQuotes adds the "quotes" edges to the MovieQuote entity.
func (mu *MovieUpdate) AddQuotes(m ...*MovieQuote) *MovieUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mu.AddQuoteIDs(ids...)
}

// Mutation returns the MovieMutation object of the builder.
func (mu *MovieUpdate) Mutation() *MovieMutation {
	return mu.mutation
}

// ClearCategory clears all "category" edges to the Category entity.
func (mu *MovieUpdate) ClearCategory() *MovieUpdate {
	mu.mutation.ClearCategory()
	return mu
}

// RemoveCategoryIDs removes the "category" edge to Category entities by IDs.
func (mu *MovieUpdate) RemoveCategoryIDs(ids ...int) *MovieUpdate {
	mu.mutation.RemoveCategoryIDs(ids...)
	return mu
}

// RemoveCategory removes "category" edges to Category entities.
func (mu *MovieUpdate) RemoveCategory(c ...*Category) *MovieUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return mu.RemoveCategoryIDs(ids...)
}

// ClearCharacters clears all "characters" edges to the Character entity.
func (mu *MovieUpdate) ClearCharacters() *MovieUpdate {
	mu.mutation.ClearCharacters()
	return mu
}

// RemoveCharacterIDs removes the "characters" edge to Character entities by IDs.
func (mu *MovieUpdate) RemoveCharacterIDs(ids ...int) *MovieUpdate {
	mu.mutation.RemoveCharacterIDs(ids...)
	return mu
}

// RemoveCharacters removes "characters" edges to Character entities.
func (mu *MovieUpdate) RemoveCharacters(c ...*Character) *MovieUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return mu.RemoveCharacterIDs(ids...)
}

// ClearQuotes clears all "quotes" edges to the MovieQuote entity.
func (mu *MovieUpdate) ClearQuotes() *MovieUpdate {
	mu.mutation.ClearQuotes()
	return mu
}

// RemoveQuoteIDs removes the "quotes" edge to MovieQuote entities by IDs.
func (mu *MovieUpdate) RemoveQuoteIDs(ids ...int) *MovieUpdate {
	mu.mutation.RemoveQuoteIDs(ids...)
	return mu
}

// RemoveQuotes removes "quotes" edges to MovieQuote entities.
func (mu *MovieUpdate) RemoveQuotes(m ...*MovieQuote) *MovieUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mu.RemoveQuoteIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MovieUpdate) Save(ctx context.Context) (int, error) {
	mu.defaults()
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MovieUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MovieUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MovieUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mu *MovieUpdate) defaults() {
	if _, ok := mu.mutation.UpdatedAt(); !ok {
		v := movie.UpdateDefaultUpdatedAt()
		mu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MovieUpdate) check() error {
	if v, ok := mu.mutation.Title(); ok {
		if err := movie.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Movie.title": %w`, err)}
		}
	}
	if v, ok := mu.mutation.Year(); ok {
		if err := movie.YearValidator(v); err != nil {
			return &ValidationError{Name: "year", err: fmt.Errorf(`ent: validator failed for field "Movie.year": %w`, err)}
		}
	}
	return nil
}

func (mu *MovieUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(movie.Table, movie.Columns, sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.UpdatedAt(); ok {
		_spec.SetField(movie.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := mu.mutation.Title(); ok {
		_spec.SetField(movie.FieldTitle, field.TypeString, value)
	}
	if value, ok := mu.mutation.Year(); ok {
		_spec.SetField(movie.FieldYear, field.TypeInt, value)
	}
	if value, ok := mu.mutation.AddedYear(); ok {
		_spec.AddField(movie.FieldYear, field.TypeInt, value)
	}
	if mu.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   movie.CategoryTable,
			Columns: movie.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedCategoryIDs(); len(nodes) > 0 && !mu.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   movie.CategoryTable,
			Columns: movie.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   movie.CategoryTable,
			Columns: movie.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.CharactersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.CharactersTable,
			Columns: movie.CharactersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedCharactersIDs(); len(nodes) > 0 && !mu.mutation.CharactersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.CharactersTable,
			Columns: movie.CharactersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.CharactersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.CharactersTable,
			Columns: movie.CharactersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.QuotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.QuotesTable,
			Columns: []string{movie.QuotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(moviequote.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedQuotesIDs(); len(nodes) > 0 && !mu.mutation.QuotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.QuotesTable,
			Columns: []string{movie.QuotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(moviequote.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.QuotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.QuotesTable,
			Columns: []string{movie.QuotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(moviequote.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{movie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MovieUpdateOne is the builder for updating a single Movie entity.
type MovieUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MovieMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (muo *MovieUpdateOne) SetUpdatedAt(t time.Time) *MovieUpdateOne {
	muo.mutation.SetUpdatedAt(t)
	return muo
}

// SetTitle sets the "title" field.
func (muo *MovieUpdateOne) SetTitle(s string) *MovieUpdateOne {
	muo.mutation.SetTitle(s)
	return muo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (muo *MovieUpdateOne) SetNillableTitle(s *string) *MovieUpdateOne {
	if s != nil {
		muo.SetTitle(*s)
	}
	return muo
}

// SetYear sets the "year" field.
func (muo *MovieUpdateOne) SetYear(i int) *MovieUpdateOne {
	muo.mutation.ResetYear()
	muo.mutation.SetYear(i)
	return muo
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (muo *MovieUpdateOne) SetNillableYear(i *int) *MovieUpdateOne {
	if i != nil {
		muo.SetYear(*i)
	}
	return muo
}

// AddYear adds i to the "year" field.
func (muo *MovieUpdateOne) AddYear(i int) *MovieUpdateOne {
	muo.mutation.AddYear(i)
	return muo
}

// AddCategoryIDs adds the "category" edge to the Category entity by IDs.
func (muo *MovieUpdateOne) AddCategoryIDs(ids ...int) *MovieUpdateOne {
	muo.mutation.AddCategoryIDs(ids...)
	return muo
}

// AddCategory adds the "category" edges to the Category entity.
func (muo *MovieUpdateOne) AddCategory(c ...*Category) *MovieUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return muo.AddCategoryIDs(ids...)
}

// AddCharacterIDs adds the "characters" edge to the Character entity by IDs.
func (muo *MovieUpdateOne) AddCharacterIDs(ids ...int) *MovieUpdateOne {
	muo.mutation.AddCharacterIDs(ids...)
	return muo
}

// AddCharacters adds the "characters" edges to the Character entity.
func (muo *MovieUpdateOne) AddCharacters(c ...*Character) *MovieUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return muo.AddCharacterIDs(ids...)
}

// AddQuoteIDs adds the "quotes" edge to the MovieQuote entity by IDs.
func (muo *MovieUpdateOne) AddQuoteIDs(ids ...int) *MovieUpdateOne {
	muo.mutation.AddQuoteIDs(ids...)
	return muo
}

// AddQuotes adds the "quotes" edges to the MovieQuote entity.
func (muo *MovieUpdateOne) AddQuotes(m ...*MovieQuote) *MovieUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return muo.AddQuoteIDs(ids...)
}

// Mutation returns the MovieMutation object of the builder.
func (muo *MovieUpdateOne) Mutation() *MovieMutation {
	return muo.mutation
}

// ClearCategory clears all "category" edges to the Category entity.
func (muo *MovieUpdateOne) ClearCategory() *MovieUpdateOne {
	muo.mutation.ClearCategory()
	return muo
}

// RemoveCategoryIDs removes the "category" edge to Category entities by IDs.
func (muo *MovieUpdateOne) RemoveCategoryIDs(ids ...int) *MovieUpdateOne {
	muo.mutation.RemoveCategoryIDs(ids...)
	return muo
}

// RemoveCategory removes "category" edges to Category entities.
func (muo *MovieUpdateOne) RemoveCategory(c ...*Category) *MovieUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return muo.RemoveCategoryIDs(ids...)
}

// ClearCharacters clears all "characters" edges to the Character entity.
func (muo *MovieUpdateOne) ClearCharacters() *MovieUpdateOne {
	muo.mutation.ClearCharacters()
	return muo
}

// RemoveCharacterIDs removes the "characters" edge to Character entities by IDs.
func (muo *MovieUpdateOne) RemoveCharacterIDs(ids ...int) *MovieUpdateOne {
	muo.mutation.RemoveCharacterIDs(ids...)
	return muo
}

// RemoveCharacters removes "characters" edges to Character entities.
func (muo *MovieUpdateOne) RemoveCharacters(c ...*Character) *MovieUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return muo.RemoveCharacterIDs(ids...)
}

// ClearQuotes clears all "quotes" edges to the MovieQuote entity.
func (muo *MovieUpdateOne) ClearQuotes() *MovieUpdateOne {
	muo.mutation.ClearQuotes()
	return muo
}

// RemoveQuoteIDs removes the "quotes" edge to MovieQuote entities by IDs.
func (muo *MovieUpdateOne) RemoveQuoteIDs(ids ...int) *MovieUpdateOne {
	muo.mutation.RemoveQuoteIDs(ids...)
	return muo
}

// RemoveQuotes removes "quotes" edges to MovieQuote entities.
func (muo *MovieUpdateOne) RemoveQuotes(m ...*MovieQuote) *MovieUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return muo.RemoveQuoteIDs(ids...)
}

// Where appends a list predicates to the MovieUpdate builder.
func (muo *MovieUpdateOne) Where(ps ...predicate.Movie) *MovieUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MovieUpdateOne) Select(field string, fields ...string) *MovieUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Movie entity.
func (muo *MovieUpdateOne) Save(ctx context.Context) (*Movie, error) {
	muo.defaults()
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MovieUpdateOne) SaveX(ctx context.Context) *Movie {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MovieUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MovieUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (muo *MovieUpdateOne) defaults() {
	if _, ok := muo.mutation.UpdatedAt(); !ok {
		v := movie.UpdateDefaultUpdatedAt()
		muo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MovieUpdateOne) check() error {
	if v, ok := muo.mutation.Title(); ok {
		if err := movie.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Movie.title": %w`, err)}
		}
	}
	if v, ok := muo.mutation.Year(); ok {
		if err := movie.YearValidator(v); err != nil {
			return &ValidationError{Name: "year", err: fmt.Errorf(`ent: validator failed for field "Movie.year": %w`, err)}
		}
	}
	return nil
}

func (muo *MovieUpdateOne) sqlSave(ctx context.Context) (_node *Movie, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(movie.Table, movie.Columns, sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Movie.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, movie.FieldID)
		for _, f := range fields {
			if !movie.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != movie.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.UpdatedAt(); ok {
		_spec.SetField(movie.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := muo.mutation.Title(); ok {
		_spec.SetField(movie.FieldTitle, field.TypeString, value)
	}
	if value, ok := muo.mutation.Year(); ok {
		_spec.SetField(movie.FieldYear, field.TypeInt, value)
	}
	if value, ok := muo.mutation.AddedYear(); ok {
		_spec.AddField(movie.FieldYear, field.TypeInt, value)
	}
	if muo.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   movie.CategoryTable,
			Columns: movie.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedCategoryIDs(); len(nodes) > 0 && !muo.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   movie.CategoryTable,
			Columns: movie.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   movie.CategoryTable,
			Columns: movie.CategoryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.CharactersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.CharactersTable,
			Columns: movie.CharactersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedCharactersIDs(); len(nodes) > 0 && !muo.mutation.CharactersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.CharactersTable,
			Columns: movie.CharactersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.CharactersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.CharactersTable,
			Columns: movie.CharactersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.QuotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.QuotesTable,
			Columns: []string{movie.QuotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(moviequote.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedQuotesIDs(); len(nodes) > 0 && !muo.mutation.QuotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.QuotesTable,
			Columns: []string{movie.QuotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(moviequote.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.QuotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.QuotesTable,
			Columns: []string{movie.QuotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(moviequote.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Movie{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{movie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
