// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/language"
	"api/ent/movie"
	"api/ent/moviequote"
	"api/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MovieQuoteQuery is the builder for querying MovieQuote entities.
type MovieQuoteQuery struct {
	config
	ctx          *QueryContext
	order        []moviequote.OrderOption
	inters       []Interceptor
	predicates   []predicate.MovieQuote
	withMovie    *MovieQuery
	withLanguage *LanguageQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MovieQuoteQuery builder.
func (mqq *MovieQuoteQuery) Where(ps ...predicate.MovieQuote) *MovieQuoteQuery {
	mqq.predicates = append(mqq.predicates, ps...)
	return mqq
}

// Limit the number of records to be returned by this query.
func (mqq *MovieQuoteQuery) Limit(limit int) *MovieQuoteQuery {
	mqq.ctx.Limit = &limit
	return mqq
}

// Offset to start from.
func (mqq *MovieQuoteQuery) Offset(offset int) *MovieQuoteQuery {
	mqq.ctx.Offset = &offset
	return mqq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mqq *MovieQuoteQuery) Unique(unique bool) *MovieQuoteQuery {
	mqq.ctx.Unique = &unique
	return mqq
}

// Order specifies how the records should be ordered.
func (mqq *MovieQuoteQuery) Order(o ...moviequote.OrderOption) *MovieQuoteQuery {
	mqq.order = append(mqq.order, o...)
	return mqq
}

// QueryMovie chains the current query on the "movie" edge.
func (mqq *MovieQuoteQuery) QueryMovie() *MovieQuery {
	query := (&MovieClient{config: mqq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mqq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(moviequote.Table, moviequote.FieldID, selector),
			sqlgraph.To(movie.Table, movie.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, moviequote.MovieTable, moviequote.MovieColumn),
		)
		fromU = sqlgraph.SetNeighbors(mqq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLanguage chains the current query on the "language" edge.
func (mqq *MovieQuoteQuery) QueryLanguage() *LanguageQuery {
	query := (&LanguageClient{config: mqq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mqq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(moviequote.Table, moviequote.FieldID, selector),
			sqlgraph.To(language.Table, language.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, moviequote.LanguageTable, moviequote.LanguageColumn),
		)
		fromU = sqlgraph.SetNeighbors(mqq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MovieQuote entity from the query.
// Returns a *NotFoundError when no MovieQuote was found.
func (mqq *MovieQuoteQuery) First(ctx context.Context) (*MovieQuote, error) {
	nodes, err := mqq.Limit(1).All(setContextOp(ctx, mqq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{moviequote.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mqq *MovieQuoteQuery) FirstX(ctx context.Context) *MovieQuote {
	node, err := mqq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MovieQuote ID from the query.
// Returns a *NotFoundError when no MovieQuote ID was found.
func (mqq *MovieQuoteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mqq.Limit(1).IDs(setContextOp(ctx, mqq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{moviequote.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mqq *MovieQuoteQuery) FirstIDX(ctx context.Context) int {
	id, err := mqq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MovieQuote entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MovieQuote entity is found.
// Returns a *NotFoundError when no MovieQuote entities are found.
func (mqq *MovieQuoteQuery) Only(ctx context.Context) (*MovieQuote, error) {
	nodes, err := mqq.Limit(2).All(setContextOp(ctx, mqq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{moviequote.Label}
	default:
		return nil, &NotSingularError{moviequote.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mqq *MovieQuoteQuery) OnlyX(ctx context.Context) *MovieQuote {
	node, err := mqq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MovieQuote ID in the query.
// Returns a *NotSingularError when more than one MovieQuote ID is found.
// Returns a *NotFoundError when no entities are found.
func (mqq *MovieQuoteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mqq.Limit(2).IDs(setContextOp(ctx, mqq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{moviequote.Label}
	default:
		err = &NotSingularError{moviequote.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mqq *MovieQuoteQuery) OnlyIDX(ctx context.Context) int {
	id, err := mqq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MovieQuotes.
func (mqq *MovieQuoteQuery) All(ctx context.Context) ([]*MovieQuote, error) {
	ctx = setContextOp(ctx, mqq.ctx, ent.OpQueryAll)
	if err := mqq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MovieQuote, *MovieQuoteQuery]()
	return withInterceptors[[]*MovieQuote](ctx, mqq, qr, mqq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mqq *MovieQuoteQuery) AllX(ctx context.Context) []*MovieQuote {
	nodes, err := mqq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MovieQuote IDs.
func (mqq *MovieQuoteQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mqq.ctx.Unique == nil && mqq.path != nil {
		mqq.Unique(true)
	}
	ctx = setContextOp(ctx, mqq.ctx, ent.OpQueryIDs)
	if err = mqq.Select(moviequote.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mqq *MovieQuoteQuery) IDsX(ctx context.Context) []int {
	ids, err := mqq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mqq *MovieQuoteQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mqq.ctx, ent.OpQueryCount)
	if err := mqq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mqq, querierCount[*MovieQuoteQuery](), mqq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mqq *MovieQuoteQuery) CountX(ctx context.Context) int {
	count, err := mqq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mqq *MovieQuoteQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mqq.ctx, ent.OpQueryExist)
	switch _, err := mqq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mqq *MovieQuoteQuery) ExistX(ctx context.Context) bool {
	exist, err := mqq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MovieQuoteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mqq *MovieQuoteQuery) Clone() *MovieQuoteQuery {
	if mqq == nil {
		return nil
	}
	return &MovieQuoteQuery{
		config:       mqq.config,
		ctx:          mqq.ctx.Clone(),
		order:        append([]moviequote.OrderOption{}, mqq.order...),
		inters:       append([]Interceptor{}, mqq.inters...),
		predicates:   append([]predicate.MovieQuote{}, mqq.predicates...),
		withMovie:    mqq.withMovie.Clone(),
		withLanguage: mqq.withLanguage.Clone(),
		// clone intermediate query.
		sql:  mqq.sql.Clone(),
		path: mqq.path,
	}
}

// WithMovie tells the query-builder to eager-load the nodes that are connected to
// the "movie" edge. The optional arguments are used to configure the query builder of the edge.
func (mqq *MovieQuoteQuery) WithMovie(opts ...func(*MovieQuery)) *MovieQuoteQuery {
	query := (&MovieClient{config: mqq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mqq.withMovie = query
	return mqq
}

// WithLanguage tells the query-builder to eager-load the nodes that are connected to
// the "language" edge. The optional arguments are used to configure the query builder of the edge.
func (mqq *MovieQuoteQuery) WithLanguage(opts ...func(*LanguageQuery)) *MovieQuoteQuery {
	query := (&LanguageClient{config: mqq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mqq.withLanguage = query
	return mqq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MovieQuote.Query().
//		GroupBy(moviequote.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mqq *MovieQuoteQuery) GroupBy(field string, fields ...string) *MovieQuoteGroupBy {
	mqq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MovieQuoteGroupBy{build: mqq}
	grbuild.flds = &mqq.ctx.Fields
	grbuild.label = moviequote.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.MovieQuote.Query().
//		Select(moviequote.FieldCreatedAt).
//		Scan(ctx, &v)
func (mqq *MovieQuoteQuery) Select(fields ...string) *MovieQuoteSelect {
	mqq.ctx.Fields = append(mqq.ctx.Fields, fields...)
	sbuild := &MovieQuoteSelect{MovieQuoteQuery: mqq}
	sbuild.label = moviequote.Label
	sbuild.flds, sbuild.scan = &mqq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MovieQuoteSelect configured with the given aggregations.
func (mqq *MovieQuoteQuery) Aggregate(fns ...AggregateFunc) *MovieQuoteSelect {
	return mqq.Select().Aggregate(fns...)
}

func (mqq *MovieQuoteQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mqq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mqq); err != nil {
				return err
			}
		}
	}
	for _, f := range mqq.ctx.Fields {
		if !moviequote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mqq.path != nil {
		prev, err := mqq.path(ctx)
		if err != nil {
			return err
		}
		mqq.sql = prev
	}
	return nil
}

func (mqq *MovieQuoteQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MovieQuote, error) {
	var (
		nodes       = []*MovieQuote{}
		withFKs     = mqq.withFKs
		_spec       = mqq.querySpec()
		loadedTypes = [2]bool{
			mqq.withMovie != nil,
			mqq.withLanguage != nil,
		}
	)
	if mqq.withMovie != nil || mqq.withLanguage != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, moviequote.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MovieQuote).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MovieQuote{config: mqq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mqq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mqq.withMovie; query != nil {
		if err := mqq.loadMovie(ctx, query, nodes, nil,
			func(n *MovieQuote, e *Movie) { n.Edges.Movie = e }); err != nil {
			return nil, err
		}
	}
	if query := mqq.withLanguage; query != nil {
		if err := mqq.loadLanguage(ctx, query, nodes, nil,
			func(n *MovieQuote, e *Language) { n.Edges.Language = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mqq *MovieQuoteQuery) loadMovie(ctx context.Context, query *MovieQuery, nodes []*MovieQuote, init func(*MovieQuote), assign func(*MovieQuote, *Movie)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MovieQuote)
	for i := range nodes {
		if nodes[i].movie_quotes == nil {
			continue
		}
		fk := *nodes[i].movie_quotes
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(movie.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "movie_quotes" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mqq *MovieQuoteQuery) loadLanguage(ctx context.Context, query *LanguageQuery, nodes []*MovieQuote, init func(*MovieQuote), assign func(*MovieQuote, *Language)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MovieQuote)
	for i := range nodes {
		if nodes[i].language_quotes == nil {
			continue
		}
		fk := *nodes[i].language_quotes
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(language.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "language_quotes" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mqq *MovieQuoteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mqq.querySpec()
	_spec.Node.Columns = mqq.ctx.Fields
	if len(mqq.ctx.Fields) > 0 {
		_spec.Unique = mqq.ctx.Unique != nil && *mqq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mqq.driver, _spec)
}

func (mqq *MovieQuoteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(moviequote.Table, moviequote.Columns, sqlgraph.NewFieldSpec(moviequote.FieldID, field.TypeInt))
	_spec.From = mqq.sql
	if unique := mqq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mqq.path != nil {
		_spec.Unique = true
	}
	if fields := mqq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, moviequote.FieldID)
		for i := range fields {
			if fields[i] != moviequote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mqq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mqq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mqq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mqq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mqq *MovieQuoteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mqq.driver.Dialect())
	t1 := builder.Table(moviequote.Table)
	columns := mqq.ctx.Fields
	if len(columns) == 0 {
		columns = moviequote.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mqq.sql != nil {
		selector = mqq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mqq.ctx.Unique != nil && *mqq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mqq.predicates {
		p(selector)
	}
	for _, p := range mqq.order {
		p(selector)
	}
	if offset := mqq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mqq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MovieQuoteGroupBy is the group-by builder for MovieQuote entities.
type MovieQuoteGroupBy struct {
	selector
	build *MovieQuoteQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mqgb *MovieQuoteGroupBy) Aggregate(fns ...AggregateFunc) *MovieQuoteGroupBy {
	mqgb.fns = append(mqgb.fns, fns...)
	return mqgb
}

// Scan applies the selector query and scans the result into the given value.
func (mqgb *MovieQuoteGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mqgb.build.ctx, ent.OpQueryGroupBy)
	if err := mqgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MovieQuoteQuery, *MovieQuoteGroupBy](ctx, mqgb.build, mqgb, mqgb.build.inters, v)
}

func (mqgb *MovieQuoteGroupBy) sqlScan(ctx context.Context, root *MovieQuoteQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mqgb.fns))
	for _, fn := range mqgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mqgb.flds)+len(mqgb.fns))
		for _, f := range *mqgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mqgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mqgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MovieQuoteSelect is the builder for selecting fields of MovieQuote entities.
type MovieQuoteSelect struct {
	*MovieQuoteQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mqs *MovieQuoteSelect) Aggregate(fns ...AggregateFunc) *MovieQuoteSelect {
	mqs.fns = append(mqs.fns, fns...)
	return mqs
}

// Scan applies the selector query and scans the result into the given value.
func (mqs *MovieQuoteSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mqs.ctx, ent.OpQuerySelect)
	if err := mqs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MovieQuoteQuery, *MovieQuoteSelect](ctx, mqs.MovieQuoteQuery, mqs, mqs.inters, v)
}

func (mqs *MovieQuoteSelect) sqlScan(ctx context.Context, root *MovieQuoteQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mqs.fns))
	for _, fn := range mqs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mqs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mqs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
