// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/moviequote"
	"api/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MovieQuoteDelete is the builder for deleting a MovieQuote entity.
type MovieQuoteDelete struct {
	config
	hooks    []Hook
	mutation *MovieQuoteMutation
}

// Where appends a list predicates to the MovieQuoteDelete builder.
func (mqd *MovieQuoteDelete) Where(ps ...predicate.MovieQuote) *MovieQuoteDelete {
	mqd.mutation.Where(ps...)
	return mqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mqd *MovieQuoteDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mqd.sqlExec, mqd.mutation, mqd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mqd *MovieQuoteDelete) ExecX(ctx context.Context) int {
	n, err := mqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mqd *MovieQuoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(moviequote.Table, sqlgraph.NewFieldSpec(moviequote.FieldID, field.TypeInt))
	if ps := mqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mqd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mqd.mutation.done = true
	return affected, err
}

// MovieQuoteDeleteOne is the builder for deleting a single MovieQuote entity.
type MovieQuoteDeleteOne struct {
	mqd *MovieQuoteDelete
}

// Where appends a list predicates to the MovieQuoteDelete builder.
func (mqdo *MovieQuoteDeleteOne) Where(ps ...predicate.MovieQuote) *MovieQuoteDeleteOne {
	mqdo.mqd.mutation.Where(ps...)
	return mqdo
}

// Exec executes the deletion query.
func (mqdo *MovieQuoteDeleteOne) Exec(ctx context.Context) error {
	n, err := mqdo.mqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{moviequote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mqdo *MovieQuoteDeleteOne) ExecX(ctx context.Context) {
	if err := mqdo.Exec(ctx); err != nil {
		panic(err)
	}
}
