-- Create "categories" table
CREATE TABLE "categories" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "categories_name_key" to table: "categories"
CREATE UNIQUE INDEX "categories_name_key" ON "categories" ("name");
-- Create "movies" table
CREATE TABLE "movies" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "title" character varying NOT NULL, "year" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create index "movies_title_key" to table: "movies"
CREATE UNIQUE INDEX "movies_title_key" ON "movies" ("title");
-- Create "category_movies" table
CREATE TABLE "category_movies" ("category_id" bigint NOT NULL, "movie_id" bigint NOT NULL, PRIMARY KEY ("category_id", "movie_id"), CONSTRAINT "category_movies_category_id" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "category_movies_movie_id" FOREIGN KEY ("movie_id") REFERENCES "movies" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "characters" table
CREATE TABLE "characters" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "name" character varying NOT NULL, "actor" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "character_name_actor" to table: "characters"
CREATE UNIQUE INDEX "character_name_actor" ON "characters" ("name", "actor");
-- Create "character_movies" table
CREATE TABLE "character_movies" ("character_id" bigint NOT NULL, "movie_id" bigint NOT NULL, PRIMARY KEY ("character_id", "movie_id"), CONSTRAINT "character_movies_character_id" FOREIGN KEY ("character_id") REFERENCES "characters" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "character_movies_movie_id" FOREIGN KEY ("movie_id") REFERENCES "movies" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "languages" table
CREATE TABLE "languages" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "languages_name_key" to table: "languages"
CREATE UNIQUE INDEX "languages_name_key" ON "languages" ("name");
-- Create "movie_quotes" table
CREATE TABLE "movie_quotes" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "quote" character varying NOT NULL, "context" character varying NOT NULL, "language_quotes" bigint NULL, "movie_quotes" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "movie_quotes_languages_quotes" FOREIGN KEY ("language_quotes") REFERENCES "languages" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "movie_quotes_movies_quotes" FOREIGN KEY ("movie_quotes") REFERENCES "movies" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "movie_quotes_quote_key" to table: "movie_quotes"
CREATE UNIQUE INDEX "movie_quotes_quote_key" ON "movie_quotes" ("quote");
