// Code generated by ent, DO NOT EDIT.

package character

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the character type in the database.
	Label = "character"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeQuotes holds the string denoting the quotes edge name in mutations.
	EdgeQuotes = "quotes"
	// Table holds the table name of the character in the database.
	Table = "characters"
	// QuotesTable is the table that holds the quotes relation/edge.
	QuotesTable = "movie_quotes"
	// QuotesInverseTable is the table name for the MovieQuote entity.
	// It exists in this package in order to avoid circular dependency with the "moviequote" package.
	QuotesInverseTable = "movie_quotes"
	// QuotesColumn is the table column denoting the quotes relation/edge.
	QuotesColumn = "character_quotes"
)

// Columns holds all SQL columns for character fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the Character queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByQuotesCount orders the results by quotes count.
func ByQuotesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newQuotesStep(), opts...)
	}
}

// ByQuotes orders the results by quotes terms.
func ByQuotes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuotesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newQuotesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuotesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, QuotesTable, QuotesColumn),
	)
}
